In [1]:
import numpy as np
import time

a = np.zeros(4); print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,)); print(f"np.zeros((4,)) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")


np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros((4,)) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4) :   a = [0.8546419  0.40316838 0.56828221 0.99704744], a shape = (4,), a data type = float64


In [ ]:
a = np.arange(10)
print(a)
print(f"a[2] shape: {a[2].shape}   ;a[2] = {a[2]}")

c = a[2:7:1]
print(f"c values : {c}") # all elements between 2 and 7 with a 1-step increase
d = a[3:]
print(f"d : {d}") # all elements from a certain index
e = a[:3]
print(f"e : {e}") # all elements up to a certain index
f = a[:]
print(f"f : {f}") # all elements

[0 1 2 3 4 5 6 7 8 9]
a[2] shape: ()   ;a[2] = 2
c values : [2 3 4 5 6]
d : [3 4 5 6 7 8 9]
e : [0 1 2]
f : [0 1 2 3 4 5 6 7 8 9]


In [ ]:
array = np.array([1,2,3,4])
print(f"array : {array}")

array_2 = - array
print(f"array_2 : {array_2}")

array_3 = np.sum(array)
print(f"array_3 : {array_3}")

array_4 = np.mean(array)
print(f"array_4 : {array_4}")

array_5 = array**2
print(f"array_5 : {array_5}")

array : [1 2 3 4]
array_2 : [-1 -2 -3 -4]
array_3 : 10
array_4 : 2.5
array_5 : [ 1  4  9 16]


In [ ]:
# Dot product

a = np.array([1,4,9])
b = np.array([9,1,4])

c = np.dot(b,a)
print(c)

49


In [23]:
matrice = np.zeros(20)
print(f"matrice : {matrice}")
matrice_4l_5c = matrice.reshape(4,-1)
print(f"matrice avec 4 lignes : {matrice_4l_5c}")

matrice : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
matrice avec 4 lignes : [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
